[package]
name = "rogue-lewis"
version = "0.1.0"
authors = ["Patrick Monaghan <0x5f.manpat@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
rand = "0.7"

gl = "0.14.0"
glutin = "0.21"

common = { git="https://github.com/manpat/common-rs.git" }